name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Sync with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add Hugging Face remote
          git remote add hf https://ramdhan9604:$HF_TOKEN@huggingface.co/spaces/ramdhan9604/Search_Engine_LLM
          
          # Fetch without merging
          git fetch hf
          
          # Create a temporary branch with HF's state
          git checkout -b hf-main hf/main
          
          # Return to main branch
          git checkout main
          
          # Merge with strategy ours (keep our version of files)
          git merge hf/main --strategy ours --allow-unrelated-histories
          
          # Push to Hugging Face
          git push hf main
          
          # Clean up
          git branch -D hf-main
